### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Dan3a** [Sonic853/Pulsoid-to-VRChat-OSC#1]
## Expected Behavior
Should start up normally and work with VRChat

## Current Behavior
Throws the following error:
```
Connected to Pulsoid.
undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at item.e (C:\Users\REDACTED\Desktop\REDACTED2\VR Stuff\pulsoid-to-vrchat-osc_v0.2.2\code\main.js:21:23)
    at Timeout._onTimeout (C:\Users\REDACTED\Desktop\REDACTED2\VR Stuff\pulsoid-to-vrchat-osc_v0.2.2\code\method.js:124:39)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by Sonic853** [comment]
Hi I updated the code, can you see if this is working? If the error still occurs, can you take a screenshot of the command line output of this program for me?
[pulsoid-to-vrchat-osc_v0.2.3_b.zip](https://github.com/Sonic853/Pulsoid-to-VRChat-OSC/files/11096406/pulsoid-to-vrchat-osc_v0.2.3_b.zip)

**Comment by Dan3a** [comment]
Hi, doesn't crash anymore, but just gives me the following error continuously:
```
Connected to Pulsoid.
data: [object Object]
Failed to parse data from Pulsoid. Skipping parameter update...
data: [object Object]
Failed to parse data from Pulsoid. Skipping parameter update...
data: [object Object]
Failed to parse data from Pulsoid. Skipping parameter update...
data: [object Object]
Failed to parse data from Pulsoid. Skipping parameter update...
data: [object Object]
```

**Comment by Sonic853** [comment]
> Hi, doesn't crash anymore, but just gives me the following error continuously:
> 
> ```
> Connected to Pulsoid.
> data: [object Object]
> Failed to parse data from Pulsoid. Skipping parameter update...
> data: [object Object]
> Failed to parse data from Pulsoid. Skipping parameter update...
> data: [object Object]
> Failed to parse data from Pulsoid. Skipping parameter update...
> data: [object Object]
> Failed to parse data from Pulsoid. Skipping parameter update...
> data: [object Object]
> ```

ok I updated the code again, can you try again?
[pulsoid-to-vrchat-osc_v0.2.3_b1.zip](https://github.com/Sonic853/Pulsoid-to-VRChat-OSC/files/11104357/pulsoid-to-vrchat-osc_v0.2.3_b1.zip)

**Comment by SK-415** [comment]
I met the same problem and `pulsoid-to-vrchat-osc_v0.2.3_b1.zip` works good for me.

**Comment by Sonic853** [comment]
> I met the same problem and `pulsoid-to-vrchat-osc_v0.2.3_b1.zip` works good for me.

OK I release a version to fix this issues
